color: null
description: null
fieldLayouts:
  3cf6946c-03ec-46b0-96e7-1be89a5580c2:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-26T13:38:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c17e37d1-2245-4a08-ae7a-f3b635cb8da8 # Bilder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c42aee15-bab8-45ff-ac0c-135aff85396a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6910b717-1f20-4049-9789-5f64dd05eae6
        userCondition: null
handle: blockFooterImages
hasTitleField: false
icon: null
name: Bilder
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
