color: null
description: null
fieldLayouts:
  3fa79bf7-b742-4721-955c-a2ecbc6090c7:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-27T15:55:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: da708e2a-e183-4911-b43a-60760107ba57 # Header
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 051c90cd-4856-4a24-900a-f0391eb7c574
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-27T15:57:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 88584328-05ce-4123-8ba3-5fa20483c0c1 # Preiskarten
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f02d3428-0ec8-4325-ad8e-a3c9200529a5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 824bf036-f7be-4f80-9a2d-65944e3c7528
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-27T15:57:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 109ab20e-f068-4d1d-999d-07f67e1ab0f5 # Style
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: baba3cdf-13a6-46cc-a5f9-5970c4f0c8dc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-04T12:12:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ba7f1da6-f4c1-4e0f-a8db-58e1fcf1f084 # Preiskarten Layout
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea3a3ea6-b9db-4ddb-af05-e036dfd86922
            userCondition: null
            warning: null
            width: 100
        name: Style
        uid: 689972f4-740f-4adf-bf55-445eb1818fe2
        userCondition: null
handle: blockPricing
hasTitleField: false
icon: tags
name: Pricing
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{header.mainTitle}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
