color: null
description: null
fieldLayouts:
  17ad7859-1055-4b58-b9e3-04bfbe311092:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-27T10:07:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: da708e2a-e183-4911-b43a-60760107ba57 # Header
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76d76514-63fc-4eac-b218-fb5c64f89fd1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 20537eb9-7f18-418b-bcfe-c017ef3f00c7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-27T10:07:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 109ab20e-f068-4d1d-999d-07f67e1ab0f5 # Style
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 266a0dde-4ade-4206-a506-d3348bfecf69
            userCondition: null
            warning: null
            width: 100
        name: Style
        uid: 9f054dd6-f81c-4b0b-a9fc-d761adae3f3e
        userCondition: null
handle: blockSimpleHeadingText
hasTitleField: false
icon: paragraph
name: 'Einfache Überschrift & Text'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{header.mainTitle}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
