color: null
description: null
fieldLayouts:
  649565c3-bd2c-445d-a20d-28dfd4040521:
    cardThumbAlignment: start
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-25T19:41:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: da708e2a-e183-4911-b43a-60760107ba57 # Header
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 30798b1b-cb61-4f15-91a1-206aef28acf9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-25T19:41:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1f0ba122-7b45-4e01-80b5-f388978b5342 # Bild
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43d5b97a-1630-4326-983d-fe748a3fa3b9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-25T19:41:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3a4974cb-b09b-4396-bc7d-dd1c1cb28121 # Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b066bc0f-d314-4c69-9f8f-bc72b7472fda
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6dbe460c-a501-436d-8e28-4b5659864160
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-27T12:49:39+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2257a735-8343-4931-9f79-9aa55499b95c # Textausrichtung Überschrift
            handle: null
            includeInCards: false
            instructions: null
            label: Textausrichtung
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb5e8343-6779-4056-89fe-5c02f1b10769
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-25T19:41:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0ea378fd-b7a4-446a-b36f-951d78786afa # Link
            handle: null
            includeInCards: false
            instructions: null
            label: 'Link / Button'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cfb78662-53d7-4e94-bff9-70c4bb7414c2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-01T20:10:40+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3326d64-1a0a-4924-a8fb-f7a08ac6587c # Schriftfarbe
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 869eaf5e-0697-49ca-b4ed-6f9b9d70d993
            userCondition: null
            warning: null
            width: 100
        name: Style
        uid: e44cbf13-a817-43c5-a5e3-8d1b9fbc333e
        userCondition: null
handle: blockHeaderHeroImage
hasTitleField: false
icon: rocket-launch
name: 'Bild & Text'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{header.mainTitle}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
