color: null
description: null
fieldLayouts:
  7b1c3b98-0fa0-4194-87e7-45ee795eccaf:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-27T15:25:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: da708e2a-e183-4911-b43a-60760107ba57 # Header
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8135244d-697a-4cd1-bce0-ca795c1504d2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-27T15:25:37+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 81c4bd23-9b33-4fa3-88d6-696c488cc702
            userCondition: null
          -
            dateAdded: '2025-07-27T15:25:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ee28f01a-b0d0-4dbd-9ac6-ee20414e94d5 # Pages
            handle: null
            includeInCards: false
            instructions: null
            label: Seiten
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c3346c0-e9f4-4d47-9860-a3e21ef21282
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a8e68e0e-1f29-42ff-a77a-786c12c765ba
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-27T15:25:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 109ab20e-f068-4d1d-999d-07f67e1ab0f5 # Style
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 140e72af-5906-47a4-a36e-bec5af20782f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-27T15:25:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7f5cd571-d7d1-45d8-a365-a67566facbca # Spalten
            handle: null
            includeInCards: false
            instructions: null
            label: 'Spalten Layout'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21e4fd16-9b8c-455a-9a84-66411fbe960f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-27T15:28:15+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 704e2ceb-08e7-4581-b06a-ba88cc2c0eb2 # Layout Teaser Grid
            handle: null
            includeInCards: false
            instructions: null
            label: Darstellung
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 656a51ef-668d-4167-9157-7012a4b5b314
            userCondition: null
            warning: null
            width: 100
        name: Style
        uid: 4c3b08e8-f76f-4f7d-aea0-3c5744e0caea
        userCondition: null
handle: blockTeaserGrid
hasTitleField: false
icon: table-cells
name: 'Teaser Grid'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{header.mainTitle}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
