color: null
description: null
fieldLayouts:
  458e6a10-052d-4fd3-88fa-84d5287e14c8:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-27T13:49:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: da708e2a-e183-4911-b43a-60760107ba57 # Header
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05fd6ea6-dd4a-490b-a50d-7520676f313f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-27T13:49:09+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 030a8702-a879-4364-9a90-1629a7c617d4
            userCondition: null
          -
            dateAdded: '2025-07-27T13:49:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0d6781e0-d456-46c9-8723-480d8fd5a4e6 # Kunden
            handle: null
            includeInCards: false
            instructions: null
            label: Kunden
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2440f744-7a2f-44e9-ad13-6568119cd3f7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7ad43d35-adc8-416c-ab23-de880c842343
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-27T13:49:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 109ab20e-f068-4d1d-999d-07f67e1ab0f5 # Erscheinungsbild
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0e1d327-b796-4b0b-8e81-777d41de9061
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-27T13:52:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7f5cd571-d7d1-45d8-a365-a67566facbca # Spalten
            handle: clientColumns
            includeInCards: false
            instructions: 'Gib hier an, in wie viele Spalten deine Kundenlogos angezeigt werden sollen.'
            label: 'Spalten Layout'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a2941ee-aa49-4651-bce9-e32f5c0c44e6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-27T13:52:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ac0c441c-23c2-44cf-ac5a-a58bef4202b3 # Client Gallery View
            handle: null
            includeInCards: false
            instructions: null
            label: Darstellung
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23515f74-88e0-4fcd-81a8-5ac1346482aa
            userCondition: null
            warning: null
            width: 100
        name: Style
        uid: 1d7a7f9c-4c32-4c15-983d-fe3dde3fdcda
        userCondition: null
handle: blockClients
hasTitleField: false
icon: circles-overlap-3
name: Kundenlogos
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{header.mainTitle}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
