color: null
description: null
fieldLayouts:
  63e43634-19b6-4a89-a343-f73aa29985c1:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:5f5129e9-730c-42ed-94f8-78a7223ac724'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-27T10:22:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f7cf0c11-6724-459d-bb73-4ab842d76701 # Text
            handle: text
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f5129e9-730c-42ed-94f8-78a7223ac724
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 826871c8-3d66-40b4-b4bd-95adde5689fe
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-27T10:22:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 109ab20e-f068-4d1d-999d-07f67e1ab0f5 # Erscheinungsbild
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc9e5a03-836d-4032-8f92-3a34989f8657
            userCondition: null
            warning: null
            width: 100
        name: Style
        uid: 7a8461ca-f491-433e-b8de-30948b57c862
        userCondition: null
handle: blockSimpleText
hasTitleField: false
icon: align-justify
name: 'Einfacher Text'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
