color: null
fieldLayouts:
  80f5dbb5-6307-4279-b9de-7f93b2b8f01c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-07T17:55:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 629dd416-ae95-4507-bfdb-28b83d47e603 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: Button
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a5c18c0-5f42-4260-bbd1-83ec92cd75df
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-07T20:22:36+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: ca12b1c0-9f3a-4519-9751-58bc32eac446
            userCondition: null
          -
            dateAdded: '2025-04-07T20:09:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e6fd663a-5010-4845-8a71-707af08f8df0 # Größe
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eb1c6ec5-bc0b-429c-bd28-159c9f055bcb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-07T20:22:36+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 21fa6522-ab08-4fa2-a3c5-94fd6f2105be
            userCondition: null
          -
            dateAdded: '2025-04-07T20:00:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: de587eda-41a2-4051-98f4-d4dcb6e7ffc5 # Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e303c288-0fb7-4e4a-aef4-c141a17e861f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-07T20:22:36+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 583545e8-831d-401f-a787-467794788a4f
            userCondition: null
          -
            dateAdded: '2025-04-07T20:19:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 892c0757-21b2-4ec0-813f-ed69f6db7b88 # Layout Button
            handle: null
            includeInCards: false
            instructions: null
            label: Layout
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c6940cc-9185-429f-a29e-11909e0568d2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 12012fe5-da44-49c6-9d54-4a7011c85d5d
        userCondition: null
handle: button
hasTitleField: false
icon: null
name: Button
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{linkField.label}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
