color: null
description: null
fieldLayouts:
  2c058be8-4e55-40b2-88ca-ef1706c1e500:
    cardThumbAlignment: start
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-27T14:32:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: de587eda-41a2-4051-98f4-d4dcb6e7ffc5 # Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd7e0b92-e6a5-44d0-8133-d9ae90abf1c2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-27T14:32:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 406dc2e0-2fac-4dd3-944e-c29ad54cd3f5 # Text
            handle: question
            includeInCards: false
            instructions: null
            label: Frage
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2382f0a1-080c-4cde-875c-2fa671cef022
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-27T14:32:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f7cf0c11-6724-459d-bb73-4ab842d76701 # Text
            handle: answer
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef08e837-7bd8-4d0b-8be0-44b466820249
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 26c36b39-4c86-4923-adfa-85c2dfab94c8
        userCondition: null
handle: faq
hasTitleField: false
icon: null
name: FAQ
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{question}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
