color: null
description: null
fieldLayouts:
  eae1bbc2-2292-493e-852c-6913ed9329cb:
    cardThumbAlignment: start
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-27T14:25:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: de587eda-41a2-4051-98f4-d4dcb6e7ffc5 # Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2997ca0d-95bd-449c-a2ae-17c5af0b4909
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-27T14:25:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 406dc2e0-2fac-4dd3-944e-c29ad54cd3f5 # Text
            handle: heading
            includeInCards: false
            instructions: null
            label: Überschrift
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 576e6843-176b-4ec7-8dca-2ffdf4263b6a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 53cee17f-ca2e-40dd-a4ab-e7acb76f2bc7
        userCondition: null
handle: featureWithIcon
hasTitleField: false
icon: null
name: 'Feature with Icon'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{heading}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
