color: red
fieldLayouts:
  a6f91219-5af6-4393-af29-103b13c925ae:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-07T17:05:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 406dc2e0-2fac-4dd3-944e-c29ad54cd3f5 # Text
            handle: internalTitle
            includeInCards: false
            instructions: null
            label: 'Interne Bezeichnung'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7f273d1-8d78-4d01-a072-cb166b38566c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-07T19:52:10+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 65b330ea-7cf0-4f05-a6a8-9221d8744f4e
            userCondition: null
          -
            dateAdded: '2025-04-07T17:05:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5041a65c-f3fb-4ee0-868a-7473bfa5d4a9 # Überschrift
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78a6f573-b01d-4076-bf53-91121286e66f
            userCondition: null
            warning: null
            width: 100
        name: Überschrift
        uid: 50ca12f5-7dcc-4f48-bb95-521221080010
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-07T17:19:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f7cf0c11-6724-459d-bb73-4ab842d76701 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5de619b1-95e7-4ab9-a755-1f7d423d3b83
            userCondition: null
            warning: null
            width: 100
        name: Text
        uid: 1ea19a9e-a524-4d18-a63b-ad28844eabb3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-07T17:27:30+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1f0ba122-7b45-4e01-80b5-f388978b5342 # Bild
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 364ff7a3-eef4-40b8-a2f0-f8a5b31107b9
            userCondition: null
            warning: null
            width: 100
        name: Bild
        uid: 9425c0e9-83a4-42e4-963c-54ec77374426
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-07T18:17:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e7bbb599-f3a7-4c48-9388-3f89b04159f7 # Buttons
            handle: null
            includeInCards: false
            instructions: null
            label: Buttons
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f465d3b-15b5-4ce3-9c0b-d282b5509057
            userCondition: null
            warning: null
            width: 100
        name: Buttons
        uid: 27bc3b83-5ea7-44a3-83a8-78a45e5f1776
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-07T19:47:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a20c2e3f-537e-438b-a0c6-0b150ceaf065 # Layout
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a065d105-2f53-4056-8c92-fdb9c3bc83bb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-07T20:43:38+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 472e458d-b06e-4a4d-a434-e0332907dad0
            userCondition: null
          -
            dateAdded: '2025-04-07T17:35:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cd2fd189-80e9-4cbd-b833-97e0a91c8bbc # Farbe
            handle: backgroundColor
            includeInCards: false
            instructions: null
            label: Hintergrundfarbe
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5199cccf-9be4-42a4-9abc-c6a4792afbe4
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-04-07T17:35:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1f0ba122-7b45-4e01-80b5-f388978b5342 # Bild
            handle: backgroundImage
            includeInCards: false
            instructions: null
            label: Hintergrundbild
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02e278b6-776a-4cb4-9ada-38992732079e
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-04-07T20:43:38+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 397272b8-83c5-41cc-abf9-fe5dd51100b7
            userCondition: null
          -
            dateAdded: '2025-04-07T20:43:38+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: da5bb037-c378-44b6-bf51-4988a6b632b8 # Trennform
            handle: layoutShapeDividerTop
            includeInCards: false
            instructions: null
            label: 'Trennform oben'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9cfdb0e8-1cd4-4aa8-b8fb-a05d8cced912
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-04-07T20:43:38+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: da5bb037-c378-44b6-bf51-4988a6b632b8 # Trennform
            handle: layoutShapeDividerBottom
            includeInCards: false
            instructions: null
            label: 'Trennform unten'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23b610b1-57ac-497d-9834-b18ea2625ac8
            userCondition: null
            warning: null
            width: 50
        name: Design
        uid: fff8c487-30ab-4f3e-9754-7cc6feda5deb
        userCondition: null
handle: feature
hasTitleField: false
icon: address-card
name: 'Bild & Text'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{internalTitle}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
