color: null
description: null
fieldLayouts:
  1c09e011-5211-4dab-be2d-0e6132fc7e3f:
    cardThumbAlignment: start
    cardView:
      - link
      - 'layoutElement:3cdaef96-6f3e-4a2c-8a73-ef21c977e9f9'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-27T14:22:03+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1f0ba122-7b45-4e01-80b5-f388978b5342 # Bild
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0adba70-0db1-4bef-adb9-a320e4b38aeb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-27T14:22:03+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 406dc2e0-2fac-4dd3-944e-c29ad54cd3f5 # Text
            handle: heading
            includeInCards: false
            instructions: null
            label: Überschrift
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 412736e6-60b1-44a6-aff2-f07c73f1babb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-27T14:22:03+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2b230794-c72c-4b65-be8f-f35f22c95db2 # Text
            handle: text
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9fffac82-caf3-4d69-a6ef-28404f50e95f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-27T14:22:03+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 629dd416-ae95-4507-bfdb-28b83d47e603 # Link
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3cdaef96-6f3e-4a2c-8a73-ef21c977e9f9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 82114daa-b01d-4db0-91a6-60d8395e3c68
        userCondition: null
handle: featureWithImageTextLink
hasTitleField: false
icon: null
name: 'Feature with Image, Text & Link'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{heading}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
