color: null
description: null
fieldLayouts:
  b13d4f6b-0389-4f4d-bf78-f71e7150f949:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-01T10:30:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: de587eda-41a2-4051-98f4-d4dcb6e7ffc5 # Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac5235a5-2771-423b-b91e-2ff726317cf5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-01T10:30:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 406dc2e0-2fac-4dd3-944e-c29ad54cd3f5 # Text
            handle: heading
            includeInCards: false
            instructions: null
            label: Überschrift
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fdc68c5-cfa2-46e2-b883-13b6fc90a40c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-01T10:32:25+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2b230794-c72c-4b65-be8f-f35f22c95db2 # Text
            handle: text
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3e34109-988c-4da7-b338-472657633c06
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 230a6102-08b8-46a7-82d7-4c314ccae9a7
        userCondition: null
handle: featureWithIconText
hasTitleField: false
icon: null
name: 'Feature with Icon Text'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{heading}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
