color: null
fieldLayouts:
  da416f13-b1e0-4b59-8616-38812c7746c7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-07T16:39:41+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Überschrift
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2ed035dd-c8c9-4c62-b86b-4c40aed9165c
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-04-07T16:46:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 95dbab60-df92-47c3-a001-8b5be0df71fb # Überschriftenformat
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8c44f7d-b172-43f1-83da-b8f02c09e2e2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-07T16:46:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 406dc2e0-2fac-4dd3-944e-c29ad54cd3f5 # Text
            handle: subTitle
            includeInCards: false
            instructions: null
            label: Unterüberschrift
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 471cd74d-efd6-4dd5-bd3a-6a9776eb8570
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e00efa59-c257-4922-9d7d-8b0cd47d5ee8
        userCondition: null
handle: heading
hasTitleField: true
icon: null
name: Überschrift
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
