color: null
fieldLayouts:
  55278945-d834-421d-86c0-7ba2db698935:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-28T14:37:30+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e05ce2ae-d576-483e-bd3f-a35203340d13
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-07T16:49:07+00:00'
            elementCondition: null
            fieldUid: 171c6317-fef7-4fb9-a710-297896fb9f55 # Content Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84baacf0-3cfa-4ca0-a4ad-987118fd2238
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d53e84ca-3fe0-4c9b-9831-b11dc01c1b7c
        userCondition: null
handle: page
hasTitleField: true
icon: null
name: Page
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
