headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: Default
options:
  alignment:
    options:
      - left
      - right
  fontSize:
    options:
      - tiny
      - small
      - big
      - huge
toolbar:
  - heading
  - '|'
  - alignment
  - '|'
  - bold
  - italic
  - blockQuote
  - strikethrough
  - '|'
  - link
  - '|'
  - fontSize
  - fontColor
  - fontBackgroundColor
  - bulletedList
  - numberedList
  - horizontalLine
  - '|'
  - insertTable
  - '|'
  - createEntry
