columnSuffix: null
handle: alignment
instructions: null
name: 'Textausrichtung Überschrift'
searchable: false
settings:
  customOptions: false
  iconsOnly: true
  options:
    -
      __assoc__:
        -
          - label
          - Links
        -
          - value
          - text-start
        -
          - icon
          - align-left
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Mitte
        -
          - value
          - text-center
        -
          - icon
          - align-center
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Rechts
        -
          - value
          - text-end
        -
          - icon
          - align-right
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\ButtonGroup
