columnSuffix: null
handle: alignmentFeatures
instructions: null
name: 'Ausrichtung der Feature-Inhalten'
searchable: false
settings:
  customOptions: false
  iconsOnly: false
  options:
    -
      __assoc__:
        -
          - label
          - Links
        -
          - value
          - left
        -
          - icon
          - border-left
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Zentriert
        -
          - value
          - center
        -
          - icon
          - border-center-v
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\ButtonGroup
