columnSuffix: null
handle: buttonSize
instructions: null
name: Größe
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - XS
        -
          - value
          - mini
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - S
        -
          - value
          - small
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - M
        -
          - value
          - default
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - L
        -
          - value
          - large
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - XL
        -
          - value
          - xlarge
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\Dropdown
