columnSuffix: null
handle: buttonAlignment
instructions: null
name: 'Button Alignment'
searchable: false
settings:
  customOptions: false
  iconsOnly: false
  options:
    -
      __assoc__:
        -
          - label
          - Oben
        -
          - value
          - top
        -
          - icon
          - border-top
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - rechts
        -
          - value
          - right
        -
          - icon
          - border-right
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - unten
        -
          - value
          - bottom
        -
          - icon
          - border-bottom
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - links
        -
          - value
          - left
        -
          - icon
          - border-left
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\ButtonGroup
