columnSuffix: null
handle: columns
instructions: 'Gib hier an, in wie viele Spalten deine Features angezeigt werden sollen.'
name: Spalten
searchable: false
settings:
  customOptions: false
  iconsOnly: true
  options:
    -
      __assoc__:
        -
          - label
          - '1'
        -
          - value
          - '12'
        -
          - icon
          - '1'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2'
        -
          - value
          - '6'
        -
          - icon
          - '2'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '3'
        -
          - value
          - '4'
        -
          - icon
          - '3'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - '4'
        -
          - value
          - '3'
        -
          - icon
          - '4'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '6'
        -
          - value
          - '2'
        -
          - icon
          - '6'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\ButtonGroup
