columnSuffix: null
handle: faqs
instructions: null
name: FAQs
searchable: false
settings:
  createButtonLabel: 'Frage & Antwort hinzufügen'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - c6fa7de8-e627-4b9e-9f39-07b394aa97d2 # FAQ
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: none
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
