columnSuffix: null
handle: headingTag
instructions: 'Wähle hier das Format deiner Überschrift aus. Bitte beachte, dass h1 nur einmal pro Seite und als erste Überschrift verwendet werden soll.'
name: Überschriftenformat
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - h1
        -
          - value
          - h1
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - h2
        -
          - value
          - h2
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - h3
        -
          - value
          - h3
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - h4
        -
          - value
          - h4
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - h5
        -
          - value
          - h5
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - h6
        -
          - value
          - h6
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\Dropdown
