columnSuffix: null
handle: image
instructions: null
name: Bild
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: true
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:96b0fd30-1d38-48e4-a19f-88765ec3b0dc' # Ansgar
  defaultUploadLocationSubpath: '{site.handle}'
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:96b0fd30-1d38-48e4-a19f-88765ec3b0dc' # Ansgar
  restrictedLocationSubpath: null
  selectionLabel: 'Bild auswählen'
  showCardsInGrid: false
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
