columnSuffix: null
handle: imagePosition
instructions: 'Stelle hier ein, in welcher Position das Bild zum Text stehen soll.'
name: Bildposition
searchable: false
settings:
  customOptions: false
  iconsOnly: false
  options:
    -
      __assoc__:
        -
          - label
          - Links
        -
          - value
          - left
        -
          - icon
          - border-left
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Rechts
        -
          - value
          - right
        -
          - icon
          - border-right
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Oberhalb
        -
          - value
          - top
        -
          - icon
          - border-top
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Unterhalb
        -
          - value
          - bottom
        -
          - icon
          - border-bottom
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Hintergrund
        -
          - value
          - background
        -
          - icon
          - expand-wide
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\ButtonGroup
