columnSuffix: null
handle: layoutFooter
instructions: null
name: 'Layout Fußzeile'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - '3 Spalten: Logo & Slogan, Links, Social Media'
        -
          - value
          - 3SpaltenLogoSloganLinksSocialMedia
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - '3 Spalten: Logo & Adresse, Links, Social Media'
        -
          - value
          - 3SpaltenLogoAdresseLinksSocialMedia
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\Dropdown
