columnSuffix: null
handle: lightswitch
instructions: null
name: Lightswitch
searchable: false
settings:
  default: false
  offLabel: Nein
  onLabel: Ja
translationKeyFormat: null
translationMethod: site
type: craft\fields\Lightswitch
