columnSuffix: null
handle: links
instructions: null
name: Links
searchable: false
settings:
  createButtonLabel: 'Neuen Link erstellen'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 713abf29-eeaa-4e35-8972-cf9602c998c1 # Link
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: none
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
