columnSuffix: null
handle: linkField
instructions: null
name: Link
searchable: false
settings:
  advancedFields:
    - title
    - target
  fullGraphqlData: true
  maxLength: 255
  showLabelField: true
  typeSettings:
    __assoc__:
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - showUnpermittedSections
              - '1'
            -
              - showUnpermittedEntries
              - '1'
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - ''
            -
              - allowCustomSchemes
              - ''
  types:
    - entry
    - url
    - email
    - tel
translationKeyFormat: null
translationMethod: site
type: craft\fields\Link
