columnSuffix: null
handle: pricingFeaturesTable
instructions: null
name: 'Pricing Features Table'
searchable: false
settings:
  addRowLabel: 'Zeile hinzufügen'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Text
            -
              - handle
              - text
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: site
type: craft\fields\Table
