columnSuffix: null
handle: richtextsimple70
instructions: 'Die Texteingabe ist auf 12 Wörter begrenzt.'
name: Text
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  characterLimit: null
  ckeConfig: d23f9520-b61b-4ceb-a796-93047c7cfbd0 # BoldItalic
  createButtonLabel: null
  defaultTransform: null
  expandEntryButtons: false
  fullGraphqlData: true
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: 12
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
