columnSuffix: null
handle: styleIconlistSimple
instructions: null
name: 'Style Iconlist'
searchable: false
settings:
  customOptions: false
  iconsOnly: false
  options:
    -
      __assoc__:
        -
          - label
          - Einfach
        -
          - value
          - simple
        -
          - icon
          - check
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Umrahmt
        -
          - value
          - border
        -
          - icon
          - border-outer
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Hintergrundfarbe
        -
          - value
          - background
        -
          - icon
          - fill-drip
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\ButtonGroup
