columnSuffix: null
handle: testimonials
instructions: null
name: Kundenmeinungen
searchable: false
settings:
  createButtonLabel: 'Kundenmeinung hinzufügen'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - e60a02de-05e2-4117-89c4-783032e024f8 # Testimonial
        -
          - name
          - Kundenmeinung
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: none
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
