fieldLayouts:
  b77763d1-f0f6-4879-928e-d545e3576da8:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-29T13:34:33+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Trage hier die Links zu deinen Social Media Profilen ein. Die Links werden im Fußbereich deiner Webseite angezeigt.'
            type: craft\fieldlayoutelements\Tip
            uid: af484091-b56d-46c7-a6d3-081ab4661728
            userCondition: null
          -
            dateAdded: '2025-08-26T21:32:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a3769b71-8bd5-41fa-9c15-6928ab790816 # Externer Link
            handle: facebook
            includeInCards: false
            instructions: null
            label: Facebook
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e5290b8-2358-4cbc-9f6c-ace7c94cd4a9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-26T21:32:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a3769b71-8bd5-41fa-9c15-6928ab790816 # Externer Link
            handle: instagram
            includeInCards: false
            instructions: null
            label: Instagram
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 363f535d-7ab3-4ff4-9a96-8085298ae010
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-26T21:32:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a3769b71-8bd5-41fa-9c15-6928ab790816 # Externer Link
            handle: pinterest
            includeInCards: false
            instructions: null
            label: Pinterest
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3fc43b8f-0bb4-4b3f-8e62-1cdb18db9b7d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-26T21:32:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a3769b71-8bd5-41fa-9c15-6928ab790816 # Externer Link
            handle: twitter
            includeInCards: false
            instructions: null
            label: 'Twitter / X'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e8b1049-6b63-49b0-a747-3aec16a24f03
            userCondition: null
            warning: null
            width: 100
        name: 'Social Media'
        uid: 7ab6fcc4-ce20-47e3-bdcc-2ab1a832f343
        userCondition: null
handle: socialMedia
name: 'Social Media'
sortOrder: 2
